# Generated by Django 4.1.1 on 2022-09-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibasic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filename', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('Createdby', models.CharField(max_length=100)),
                ('Assignedto', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
